<?php
    require 'main-links/links.php';
    session_start();
?>
    <!-------------------- Header Start -------------------->
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark  bg-dark" >
            <div class="container">
                <a class="navbar-brand" href="">
                    Login Panel
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0  m-auto">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="#">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="#">Blog</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="#">Pages</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="#">Contact</a>
                        </li>
                    </ul>
                    <div class="avatar px-2 text-white">
                        <span>
                            Hello, 
                            <?php echo $_SESSION['first_name']; ?>
                        </span>
                        <img src="images/<?php echo $_SESSION['profile_pic']; ?>">
                        <div class="avatar_profile" style="margin-left:-25px;">
                            <a href="edit.php?id=<?php echo $_SESSION['user_id']; ?>" class="btn btn-secondary text-start w-100">Edit Profile</a>
                            <a href="delete.php?id=<?php echo $_SESSION['user_id']; ?>" class="btn btn-secondary text-start w-100">Delete Accoutn</a>
                            <a href="logout.php?id=<?php echo $_SESSION['user_id']; ?>" class="btn btn-secondary text-start w-100">Logout</a>
                        </div><!--avatar_profile-->
                    </div><!--avatar-->
                </div><!--collapse-->
            </div><!--container-->
        </nav>
    </header>
    <!-------------------- Header End -------------------->


    <section>
        <p class="text-danger m-5">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatibus repellat doloremque dolorum ut dolorem blanditiis officia rerum. Alias fugiat ipsum maiores veritatis repellat cumque expedita assumenda, excepturi libero nobis nulla sequi, vel officia veniam cupiditate optio itaque a maxime delectus quis quasi fuga voluptates quaerat iure! Eos ad consequuntur provident error voluptatum soluta quasi adipisci ea eveniet, corrupti assumenda sapiente molestiae nobis dolores, veritatis omnis obcaecati expedita reiciendis hic impedit. Quod, eius. Maiores laboriosam praesentium dolore quo corporis blanditiis quasi nisi, doloremque animi voluptates ullam nobis voluptate ducimus assumenda reiciendis ad deleniti odio molestiae? Earum libero in quasi error nesciunt, fugiat quisquam cumque voluptatem. Voluptatum amet rem voluptatem expedita magnam autem quas et, saepe, voluptatibus quia cumque assumenda laborum incidunt modi at nemo? Saepe eaque maiores quos pariatur perferendis obcaecati. Voluptatum ratione explicabo, dolorem non vero maiores, earum atque voluptate delectus ducimus dolorum sequi modi? Sunt quos repudiandae molestias impedit vero repellendus molestiae, cupiditate quaerat consequatur minima tempora natus qui doloribus at illum temporibus reprehenderit fugit alias quam. Facere neque consequatur quod dolores veniam odio deleniti omnis eligendi ducimus? Tempore, sequi labore! Quidem animi accusantium nostrum harum aut vel quaerat, ipsa dolore eius magni repellendus quis accusamus asperiores rerum, sunt quos repudiandae sequi quas. Mollitia praesentium sequi voluptas rerum recusandae necessitatibus reprehenderit dolor placeat, aliquid, aut labore quos nobis, sed ad illo voluptatem facere blanditiis quam dolore incidunt dignissimos. Quas incidunt, ad nihil, illum necessitatibus sapiente porro expedita cumque deleniti tenetur odio id tempora fugit sit? Nisi in minima maiores.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatibus repellat doloremque dolorum ut dolorem blanditiis officia rerum. Alias fugiat ipsum maiores veritatis repellat cumque expedita assumenda, excepturi libero nobis nulla sequi, vel officia veniam cupiditate optio itaque a maxime delectus quis quasi fuga voluptates quaerat iure! Eos ad consequuntur provident error voluptatum soluta quasi adipisci ea eveniet, corrupti assumenda sapiente molestiae nobis dolores, veritatis omnis obcaecati expedita reiciendis hic impedit. Quod, eius. Maiores laboriosam praesentium dolore quo corporis blanditiis quasi nisi, doloremque animi voluptates ullam nobis voluptate ducimus assumenda reiciendis ad deleniti odio molestiae? Earum libero in quasi error nesciunt, fugiat quisquam cumque voluptatem. Voluptatum amet rem voluptatem expedita magnam autem quas et, saepe, voluptatibus quia cumque assumenda laborum incidunt modi at nemo? Saepe eaque maiores quos pariatur perferendis obcaecati. Voluptatum ratione explicabo, dolorem non vero maiores, earum atque voluptate delectus ducimus dolorum sequi modi? Sunt quos repudiandae molestias impedit vero repellendus molestiae, cupiditate quaerat consequatur minima tempora natus qui doloribus at illum temporibus reprehenderit fugit alias quam. Facere neque consequatur quod dolores veniam odio deleniti omnis eligendi ducimus? Tempore, sequi labore! Quidem animi accusantium nostrum harum aut vel quaerat, ipsa dolore eius magni repellendus quis accusamus asperiores rerum, sunt quos repudiandae sequi quas. Mollitia praesentium sequi voluptas rerum recusandae necessitatibus reprehenderit dolor placeat, aliquid, aut labore quos nobis, sed ad illo voluptatem facere blanditiis quam dolore incidunt dignissimos. Quas incidunt, ad nihil, illum necessitatibus sapiente porro expedita cumque deleniti tenetur odio id tempora fugit sit? Nisi in minima maiores.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatibus repellat doloremque dolorum ut dolorem blanditiis officia rerum. Alias fugiat ipsum maiores veritatis repellat cumque expedita assumenda, excepturi libero nobis nulla sequi, vel officia veniam cupiditate optio itaque a maxime delectus quis quasi fuga voluptates quaerat iure! Eos ad consequuntur provident error voluptatum soluta quasi adipisci ea eveniet, corrupti assumenda sapiente molestiae nobis dolores, veritatis omnis obcaecati expedita reiciendis hic impedit. Quod, eius. Maiores laboriosam praesentium dolore quo corporis blanditiis quasi nisi, doloremque animi voluptates ullam nobis voluptate ducimus assumenda reiciendis ad deleniti odio molestiae? Earum libero in quasi error nesciunt, fugiat quisquam cumque voluptatem. Voluptatum amet rem voluptatem expedita magnam autem quas et, saepe, voluptatibus quia cumque assumenda laborum incidunt modi at nemo? Saepe eaque maiores quos pariatur perferendis obcaecati. Voluptatum ratione explicabo, dolorem non vero maiores, earum atque voluptate delectus ducimus dolorum sequi modi? Sunt quos repudiandae molestias impedit vero repellendus molestiae, cupiditate quaerat consequatur minima tempora natus qui doloribus at illum temporibus reprehenderit fugit alias quam. Facere neque consequatur quod dolores veniam odio deleniti omnis eligendi ducimus? Tempore, sequi labore! Quidem animi accusantium nostrum harum aut vel quaerat, ipsa dolore eius magni repellendus quis accusamus asperiores rerum, sunt quos repudiandae sequi quas. Mollitia praesentium sequi voluptas rerum recusandae necessitatibus reprehenderit dolor placeat, aliquid, aut labore quos nobis, sed ad illo voluptatem facere blanditiis quam dolore incidunt dignissimos. Quas incidunt, ad nihil, illum necessitatibus sapiente porro expedita cumque deleniti tenetur odio id tempora fugit sit? Nisi in minima maiores.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatibus repellat doloremque dolorum ut dolorem blanditiis officia rerum. Alias fugiat ipsum maiores veritatis repellat cumque expedita assumenda, excepturi libero nobis nulla sequi, vel officia veniam cupiditate optio itaque a maxime delectus quis quasi fuga voluptates quaerat iure! Eos ad consequuntur provident error voluptatum soluta quasi adipisci ea eveniet, corrupti assumenda sapiente molestiae nobis dolores, veritatis omnis obcaecati expedita reiciendis hic impedit. Quod, eius. Maiores laboriosam praesentium dolore quo corporis blanditiis quasi nisi, doloremque animi voluptates ullam nobis voluptate ducimus assumenda reiciendis ad deleniti odio molestiae? Earum libero in quasi error nesciunt, fugiat quisquam cumque voluptatem. Voluptatum amet rem voluptatem expedita magnam autem quas et, saepe, voluptatibus quia cumque assumenda laborum incidunt modi at nemo? Saepe eaque maiores quos pariatur perferendis obcaecati. Voluptatum ratione explicabo, dolorem non vero maiores, earum atque voluptate delectus ducimus dolorum sequi modi? Sunt quos repudiandae molestias impedit vero repellendus molestiae, cupiditate quaerat consequatur minima tempora natus qui doloribus at illum temporibus reprehenderit fugit alias quam. Facere neque consequatur quod dolores veniam odio deleniti omnis eligendi ducimus? Tempore, sequi labore! Quidem animi accusantium nostrum harum aut vel quaerat, ipsa dolore eius magni repellendus quis accusamus asperiores rerum, sunt quos repudiandae sequi quas. Mollitia praesentium sequi voluptas rerum recusandae necessitatibus reprehenderit dolor placeat, aliquid, aut labore quos nobis, sed ad illo voluptatem facere blanditiis quam dolore incidunt dignissimos. Quas incidunt, ad nihil, illum necessitatibus sapiente porro expedita cumque deleniti tenetur odio id tempora fugit sit? Nisi in minima maiores.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatibus repellat doloremque dolorum ut dolorem blanditiis officia rerum. Alias fugiat ipsum maiores veritatis repellat cumque expedita assumenda, excepturi libero nobis nulla sequi, vel officia veniam cupiditate optio itaque a maxime delectus quis quasi fuga voluptates quaerat iure! Eos ad consequuntur provident error voluptatum soluta quasi adipisci ea eveniet, corrupti assumenda sapiente molestiae nobis dolores, veritatis omnis obcaecati expedita reiciendis hic impedit. Quod, eius. Maiores laboriosam praesentium dolore quo corporis blanditiis quasi nisi, doloremque animi voluptates ullam nobis voluptate ducimus assumenda reiciendis ad deleniti odio molestiae? Earum libero in quasi error nesciunt, fugiat quisquam cumque voluptatem. Voluptatum amet rem voluptatem expedita magnam autem quas et, saepe, voluptatibus quia cumque assumenda laborum incidunt modi at nemo? Saepe eaque maiores quos pariatur perferendis obcaecati. Voluptatum ratione explicabo, dolorem non vero maiores, earum atque voluptate delectus ducimus dolorum sequi modi? Sunt quos repudiandae molestias impedit vero repellendus molestiae, cupiditate quaerat consequatur minima tempora natus qui doloribus at illum temporibus reprehenderit fugit alias quam. Facere neque consequatur quod dolores veniam odio deleniti omnis eligendi ducimus? Tempore, sequi labore! Quidem animi accusantium nostrum harum aut vel quaerat, ipsa dolore eius magni repellendus quis accusamus asperiores rerum, sunt quos repudiandae sequi quas. Mollitia praesentium sequi voluptas rerum recusandae necessitatibus reprehenderit dolor placeat, aliquid, aut labore quos nobis, sed ad illo voluptatem facere blanditiis quam dolore incidunt dignissimos. Quas incidunt, ad nihil, illum necessitatibus sapiente porro expedita cumque deleniti tenetur odio id tempora fugit sit? Nisi in minima maiores.
        </p>
    </section>